### ISSUE TITLE
关于Apple script运行成功但没有返回结果的问题

### ISSUE THREAD

**Issue by Bufordyang** [iLern/ncm2mp3_for_mac#1]
### 感谢作者分享的`ncm2mp3`的`python`脚本！
我单独运行了`ncm2mp3.py`文件，并成功获得了`ncm`到`mp3`的转换结果文件。
但是关于Apple script的快捷指令在运行后没有得到返回结果(我已指定了`.py`地址)
由于欠缺Apple script的开发经验，这部分的debug难以进行
所以想请问作者是否方便分享该快捷指令？或者就下面的快捷指令截图给与一些指导呢？

下面是我制作的快捷指令截图（比较不确定的地方是变量的获取指令是否正确，我选择的类型是文件）：
<img width="1192" alt="image" src="https://github.com/iLern/ncm2mp3_for_mac/assets/48524140/887c8cda-aa9f-45e2-a4e7-92e80b595243">

**Comment by iLern** [comment]
试一试把python脚本的路径改成绝对路径呢，例如`/Users/xxx/Source_Code_Folder/ncm2mp3_for_mac/ncm2mp3.py`

**Comment by Bufordyang** [comment]
你好，我已收到你的邮件

**Comment by Bufordyang** [comment]
> 试一试把python脚本的路径改成绝对路径呢，例如`/Users/xxx/Source_Code_Folder/ncm2mp3_for_mac/ncm2mp3.py`

更换成绝对路径后还是得不到转换结果，但程序流却正常执行到了“转换完成”这一步，无报错信息

**Comment by Bufordyang** [comment]
这是我的快捷指令：
https://www.icloud.com/shortcuts/eca58cbb4c2b489284e0f848f1a07bd9

**Comment by iLern** [comment]
我更新了仓库，里面添加了快捷指令的文件，把里面的路径改成你自己的再试试看，会不会有什么报错信息

**Comment by Bufordyang** [comment]
> 我更新了仓库，里面添加了快捷指令的文件，把里面的路径改成你自己的再试试看，会不会有什么报错信息

### 感谢您的耐心解答，我找到了shortcuts指令的bug，并成功修复了(似乎也不能算bug)
- shortcuts指令默认使用python3当做解释器时，即位于/usr/bin/python3，使用的环境是系统自带的一个环境，这个环境里缺少相关包的依赖。而我安装了anaconda，默认使用了base环境进行脚本执行
- 因此需要再apple script中先激活conda环境，再运行python，使用下面的指令可以实现在运行python的时候指定conda环境
`set resultText to do shell script "source ~/anaconda3/bin/activate py39; python3 " & pythonScriptPath & " " & quoted form of argument`
在修改完apple script后脚本通过快捷指令成功执行。

完整的apple script如下：
```
on run {input, parameters}
	set pythonScriptPath to "YOUR ncm2mp3.py PATH"
	set argument to item 1 of input
	try
		set resultText to do shell script "source ~/anaconda3/bin/activate your_env_name; python3 " & pythonScriptPath & " " & quoted form of argument
		return resultText
	on error errMsg
		return "Error: " & errMsg
	end try
end run
```
